name: bullseye
description: A dart web framework
version: 0.0.1
homepage: https://github.com/giann/bullseye
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  darty_json: ^1.0.0
  http: ^0.13.4
  args: ^2.3.0
  logging: ^1.0.2
  ansicolor: ^2.0.1
  mysql1:
    git:
      url: git@github.com:giann/mysql1_dart.git
      ref: no-log

dev_dependencies:
  lints: ^1.0.0
