name: bullseye
description: A dart web framework
version: 0.0.1
homepage: https://github.com/giann/bullseye

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  darty_json: ^1.0.0
  http: ^0.13.4
  args: ^2.3.0

dev_dependencies:
  lints: ^1.0.0
